apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: guilhermelimasoares9/hackaton-ms-app
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-configmap
        resources:
            requests:
              cpu: 400m
